Win32 support
libhangul/libhangul pull request #72
Opened 2023-02-11 06:01 UTC by wkpark

***WIP***
VS vcxproj 추가 및 WIN32 지원을 위한 변경을 추가했습니다.
* `DynamicLibrary`지원
* `glob` 지원 문제로 `ENABLE_EXTERNAL_KEYBOARDS`는 비활성화

그밖에, `cmake` + MSYS(mingw64) 지원은 자잘한 문제로 제대로 빌드가 안되는군요.
cmake+리눅스+mingw64빌드는 아직 테스트해보지 않았습니다.

See also https://github.com/navilera/libhangul 최근(?) 작업도 참고하였습니다.

2023-02-11 13:04 UTC, choehwanjin commented
감사합니다.

그런데 조금 수정했으면 하는 부분이 있어서 커멘트를 남길 테니 좀 수정해주시면 좋겠습니다.
아니면 제가 amend해서 커밋할 수도 있으니 곤란하시면 말씀해주세요.

2023-02-11 13:41 UTC, choehwanjin reviewed
윈도우즈 플랫폼에 대해서는 별 신경을 쓰지 않고 있었는데, 작업 감사합니다.

2023-02-11 13:41 UTC, choehwanjin commented on hangul/hangulkeyboard.c
> +#endif
```
#endif /* ENABLE_EXTERNAL_KEYBOARDS */
```
처럼 주석을 추가해주시면 좋겠네요.

2023-02-11 13:41 UTC, choehwanjin commented on hangul/hanja.c
> +#endif
LIBHANGUL_DEFAULT_HANJA_DIC 환경 변수가 필요한 이유에 대해서 좀 설명 부탁드립니다.

2023-02-11 13:41 UTC, choehwanjin commented on test/test.c
> +#endif
```
#endif /* ENABLE_EXTERNAL_KEYBOARDS */
```
처럼 주석을 추가해주시면 좋겠네요.

2023-02-11 13:41 UTC, choehwanjin commented on test/test.c
> +#endif
```
#endif /* ENABLE_EXTERNAL_KEYBOARDS */
```
처럼 주석을 추가해주시면 좋겠네요.

2023-02-11 13:41 UTC, choehwanjin commented on test/test.c
> +    }
```
putenv("LIBHANGUL_KEYBOARD_PATH=" TEST_LIBHANGUL_KEYBOARD_PATH);
```
위 코드를 이렇게 바꿨으면  좋겠습니다.
path 버퍼의 크기를 설정하지 않아도 되는 코드가 되면 좋을 것 같아서 수정하고 싶네요.

2023-02-11 13:41 UTC, choehwanjin commented on win32/libhangul.def
> +EXPORTS
def 파일을 사용하기보다 DECLSPEC_EXPORT를 사용할까 합니다. 
그래서 libhangul.def 파일을 추가하지 않고 일단 프로젝트를 구성해주시면 좋을 것 같은데요.
그러면 제가 이후 LIBHANGUL_EXPORT 매크로를 헤더에 추가하는 작업을 진행할 수도 있을 것 같습니다.

혹시 def 파일을 사용해야 하는 이유가 있다면 알려주세요.
의견 부탁드립니다.

2023-02-11 14:06 UTC, wkpark commented on hangul/hanja.c
> +#endif
아.. 이건 윈도우 상에서는 시스템 상수를 컴파일시 적용하기 곤란한 부분때문에 일단 이렇게 해보았습니다. (예를 들어, `%SYSTEMROOT%` 조차도 `C:\Windows`가 아닐 수도 있는 등등. 컴파일시점에서 확정이 어려움)

2023-02-11 14:28 UTC, wkpark commented on win32/libhangul.def
> +EXPORTS
장점이 몇가지 있는데, def 파일은 사용하는 경우 소스코드에 추가/변경 없이 대부분의 컴파일러에서 문제없이 작동한다 + 심볼이 정의된 순서를 지정할 수 있어서 호환성 면에도 좋다는 것 정도입니다~ (`__declspec(dllexport)`를 사용하므로 def 없어도 무방해 보이는 zlib 프로젝트도 여전히 def를 유지하는 이유일 듯 합니다.)

See also:
https://stackoverflow.com/a/49157814/1696120

2023-02-11 16:01 UTC, wkpark commented on hangul/hanja.c
> +#endif
일단 윈도우의 경우 기본 한자 사전의 위치를 지정하기 어려우니 아예 이 부분은 빼버리고, 지정하지 않아도 컴파일시 문제없도록 고쳐봤습니다. 이 부분은 한글 키보드처럼 별도의 루틴으로 기본값을 정하거나 하는 방식을 쓰는 것이 나을 듯 한데, 이는 따로 이슈로 올리겠습니다.

2023-02-12 00:48 UTC, choehwanjin requested changes

2023-02-12 00:48 UTC, choehwanjin commented on win32/libhangul.def
> +EXPORTS
그렇군요.
하지만 함수를 변경하거나 추가할때 .def 파일까지 같이 수정해야 하니까 번거로울 것 같습니다.
헤더만 수정해서 관리하는 편이  편리할 것 같습니다.

2023-02-15 03:13 UTC, wkpark commented on win32/libhangul.def
> +EXPORTS
def파일을 일단 뺐습니다~

2023-02-26 13:07 UTC, merged